
siemens_mysql:
  host: 'rm-2ze9h45vus669c676.mysql.rds.aliyuncs.com'
  user: dev_cluster
  password: 'PqouUIyMpyU09MQT'
  port: 3306
  charset: utf8
  database: test_siemens_rpm


ajl_mysql:
  host: '127.0.0.1'
  user: cluster
  password: 'OK3iO9skpEcybGhx'
  port: 3333
  charset: utf8
  database: cluster_system
